### ISSUE TITLE
Multi-languages support

### ISSUE THREAD

**Issue by MaximeGir** [rxgx/json-calendar#24]
Problem: End user being passed days / months names in english only, need for client to translate to other languages.

Suggested solution : 
Support for multiple languages  (besides english) : French, German, Spanish, etc. 
Could be an optional parameter in the Calendar constructor, defaults to english, thus no breaking changes. 

Alternatives: 

Translation on the client using json-calendar. 

Context: I am building an API that deals with days / months name for end user (for sms, mostly) and user base is french.

**Comment by rxgx** [comment]
Thanks for the PR! I'll review this and try to get it released this week.

**Comment by rxgx** [comment]
Released! https://github.com/rxgx/json-calendar/releases/tag/v1.6.0
