### ISSUE TITLE
Weeks array is not cleared when changing month

### ISSUE THREAD

**Issue by leup** [rxgx/json-calendar#835]
**Is your feature request related to a problem? Please describe.**

Hello ! I was looking for a decent standalone calendar widget when I found your project.
I liked the idea to make my own widget based on your library.

But when I tried to change month, it adds new weeks to the array, and not reset it.
I did not find a way to reset the weeks array without instantiating a new Calendar object.
Which works but it is not very convenient. May be I did not used it properly

**Describe the solution you'd like**

Have a way to reset the weeks array or clear the array when changing month.

**Describe alternatives you've considered**

Instantiate a new Calendar object.

Thanks for sharing your work !

**Comment by leup** [comment]
Thanks for your work !

**Comment by rxgx** [comment]
@leup Thanks for finding this bug!
